exp_dir: experiments
current_exp_dir: ${exp.exp_dir}/${exp_name}
sampling_dir: ${exp.current_exp_dir}/sampling
in_process_dir: ${exp.current_exp_dir}/in_process
checkpoint_dir: ${exp.current_exp_dir}/checkpoints
best_dir: ${exp.checkpoint_dir}/best
autoencoder_prefix: 'ae_'
discriminator_prefix: 'discriminator_'
diffusion_prefix: 'diffusion_'
cm_prefix: 'cm_'